# Generated by Django 5.2.3 on 2025-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('O Positive', 'O Positive')], default='A Positive', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('India', 'India')], default='India', max_length=100)),
                ('state', models.CharField(choices=[('Assam', 'Assam')], default='Assam', max_length=100)),
                ('city', models.CharField(choices=[('Guwahati', 'Guwahati')], default='Guwahati', max_length=100)),
                ('district', models.CharField(choices=[('Kamrup', 'Kamrup')], default='Kamrup', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
