# Generated by Django 5.2.3 on 2025-07-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
